apiVersion: v1
kind: Service
metadata:
  name: service-greeting-brian-service
spec:
  ports:
  - port: 30002
    nodePort: 30002
    targetPort: 8080
  selector:
    app: service-greeting-brian
  type: NodePort
